version: "3.6"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${DATABASE_SQL_VOLUME}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: docker
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:docker@postgres:5432/jobs
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  webapp:
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - "graphql-engine"
    volumes:
      - "./client:/usr/app/"
      - "/usr/app/node_modules"
    command: "npm run build && npm run start"
