version: "3.6"
services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "${DOCKER_VOLUME_SQL_DATABASE}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: docker

  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:docker@postgres:5432/jobs
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  # TODO: figure out how to get chromedp in docker
  #  chrome-driver:
  #    image: chromedp/headless-shell:latest
  #    ports:
  #      - "9222:9222"

  #  server:
  #    build: ./server
  #    volumes:
  #      - "${SERVER_EXE_VOLUME}:/usr/src/myapp/dist"
  #    working_dir: "/usr/src/myapp"
  #    command: "go build -a -tags netgo -ldflags '-w' -o dist/job_scraper_api *.go"

  webapp:
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    working_dir: "/usr/app"
    command: "npm run start"
